[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_nft_staking = "EHbvoP4faubDYTM2EMfXz5AZSFAh1N5nw2AGNhBLDPQN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/juan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
